### ISSUE TITLE
Add some sort of method to verify the contents of the INDEX file

### ISSUE THREAD

**Issue by josegonzalez** [fisherman/fisher-index#1]
It would be nice to get some CI going on this, so that when people submit pull requests, they don't accidentally clobber the file.

For instance, it might check to ensure there are the proper number of newlines, that the urls do not 404/302, that the right content exists for a given change etc.

Not sure how the testing would work in practice, but just an idea I thought I'd throw out there.

**Comment by bucaran** [comment]
Sounds good to me. The process of submitting a PR is currently manual, but I am going to release `submit` a plugin that will take care of everything automatically, leaving me and other collaborators only responsible of merging.

I like this idea anyway and I will add it to a future milestone.

**Comment by jethrokuan** [comment]
@josegonzalez i've done some form of CI for the index. The checker is [here](https://github.com/fisherman/fisher-checker/).

Example of a build success is [here](https://travis-ci.org/fisherman/fisher-index/builds/116553142).

Perhaps we should close this issue and move the discussion to #7.

**Comment by bucaran** [comment]
Closing in favor of #7.
