### ISSUE TITLE
Store data as JSON

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisher-index#6]

**Comment by ishankhare07** [comment]
Can someone explain me what's the purpose of this index?
Also does fisherman keeps track of installed instructions like oh my zsh does in the ~/.oh-my-zsh?

**Comment by bucaran** [comment]
This index is Fisherman's external database. This is how Fisherman knows what package to install when you use a name instead of a URL or a path.

**Comment by ishankhare07** [comment]
@bucaran does fisherman store the installed packages in a local directory?
like oh-my-zsh? What is the mechanism use for installation?

**Comment by bucaran** [comment]
Installed packages are installed to XDG_CONFIG/fisherman and the relevant files; functions, completions, etc., are symlinked to the one master path that is added to fish `$fish_function_path` and `$fish_complete_path`.

The mechanism use for installation is Git.

**Comment by bucaran** [comment]
Closing as wontfix.
