### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisher-index#7]

**Comment by jethrokuan** [comment]
I think I can work on this.

**Comment by bucaran** [comment]
This is completely outside of Fisherman's realm, so we could write tests in any language.

**Comment by jethrokuan** [comment]
I'm gonna do it in go :smile:

**Comment by bucaran** [comment]
:+1:

**Comment by jethrokuan** [comment]
Tests done:

- [x] fishfile is legitimate
- [x] name is unique
- [x] url is legitimate
- [x] tags are unique
- [x] tags are legitimate

**Comment by bucaran** [comment]
@jethrokuan You rock man!

Closing as resolved.
